---

version: '3'
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data:/var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
  kapacitor:
    image: kapacitor
    ports:
      - "9092:9092"
    volumes:
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
